rtls_ids:
  id_1: "ble-pd-601283DE0245"
  id_2: "ble-pd-601283DE0246"

locations:
  home:
    robot:
      x: 0.0
      y: 0.0
      z: 0.0
      rot_x: 0.0
      rot_y: 0.0
      rot_z: 0.0
      rot_w: 0.0
    pre_pick:
      x: 0.0
      y: 0.0
      z: 0.0
      rot_x: 0.0
      rot_y: 0.0
      rot_z: 0.0
      rot_w: 0.0      
    place:
      x: 0.0
      y: 0.0
      z: 0.0
      rot_x: 0.0
      rot_y: 0.0
      rot_z: 0.0
      rot_w: 0.0
  room_1:
    pre_pick:
      x: 0.0
      y: 0.0
      z: 0.0
      rot_x: 0.0
      rot_y: 0.0
      rot_z: 0.0
      rot_w: 0.0      
    place:
      x: 0.0
      y: 0.0
      z: 0.0
      rot_x: 0.0
      rot_y: 0.0
      rot_z: 0.0
      rot_w: 0.0
  room_2:
    pre_pick:
      x: 0.0
      y: 0.0
      z: 0.0
      rot_x: 0.0
      rot_y: 0.0
      rot_z: 0.0
      rot_w: 0.0      
    place:
      x: 0.0
      y: 0.0
      z: 0.0
      rot_x: 0.0
      rot_y: 0.0
      rot_z: 0.0
      rot_w: 0.0
  room_3:
    place:
      x: 0.0
      y: 0.0
      z: 0.0
      rot_x: 0.0
      rot_y: 0.0
      rot_z: 0.0
      rot_w: 0.0
  docking_stations:
    home:
      x: 0.0
      y: 0.0
    room_1:
      x: 0.0
      y: 0.0
    room_2:
      x: 0.0
      y: 0.0
